### ISSUE TITLE
Propuesta charla sobre arquitecturas, esquemas y pruebas e2e en Angular

### ISSUE THREAD

**Issue by gpincheiraa** [ngChile/meetups#2]
## ¿Qué tipo de presentación quieres hacer?
- [x] Keynote (25-30 minutos max)
- [ ] Lightning Talk (5-10 minutos max)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Gonzalo Pincheira

## ¿Cuál es el título de tu charla?
Arquitecturas, esquemas y pruebas e2e en Angular

## Danos una descripción de tu charla (50 palabras máximo)
La idea es contar mi experiencia haciendo un fork de https://github.com/gpincheiraa/ngx-cypress-builder para modificar un comportamiento inesperado sobre un flujo de trabajo para pruebas e2e con cypress y como esto me llevó a entender como están formadas las arquitecturas, los constructores de procesos, los esquemas y el papel que cumplen los observables para poder manejar multiples procesos con Node.js. Adicional a esto a modo de probar la arquitectura presentada en un inicio, la idea es compartir un flujo de trabajo para pruebas funcionales utilizando cypress y cucumber.
 
## ¿Tienes alguna red social donde podamos contactarte?
Twitter: gpincheiraa
Github: gpincheiraa

## ¿Representas a alguna compañía o empresa?
TBD
## ¿Qué tipo de conector tiene tu notebook?

- [ ] HDMI
- [x] Mini DisplayPort
- [ ] VGA

-----------
> Muchas Gracias! 
> El equipo de Angular Chile <3

**Comment by nicoavila** [comment]
Hola @gpincheiraa . Está muy interesante el contenido de tu keynote. Crees que sea factible presentarla para el meetup de Junio?

**Comment by gpincheiraa** [comment]
Hola. Si, me anoto para Junio.

**Comment by nicoavila** [comment]
Genial!
Muchas gracias @gpincheiraa 😄
