### ISSUE TITLE
Propuesta - Testeando componentes

### ISSUE THREAD

**Issue by flakolefluk** [ngChile/meetups#4]
> Nuestros eventos se rigen por el siguiente [Código de conducta](https://github.com/ngChile/code_of_conduct) - [https://github.com/ngChile/code_of_conduct](https://github.com/ngChile/code_of_conduct) 

> Antes de suscribir una charla, recuerda revísarlo para ver si estamos en la misma onda 😊

## ¿Qué tipo de presentación quieres hacer?

- [x] Keynote (25-30 minutos max)
- [ ] Lightning Talk (5-10 minutos max)
- [ ] Avisos de trabajo / comunidades / actividades / ETC.

## ¿Cuál es tu nombre?
Ignacio Falk

## ¿Cuál es el título de tu charla?
Testeando componentes (usando testing-library) 

## Danos una descripción de tu charla (50 palabras máximo)
En desarrollo .
Exponer primero las formas de tests unitarios/integración (test aislado, shallow tests, etc.). Mencionar y enfocarme finalmente en testing-library y su uso con angular, además de sus principios y como pueden ayudar a confiar más en nuestros tests. 

## ¿Tienes alguna red social donde podamos contactarte?
twitter - github: @flakolefluk

## ¿Representas a alguna compañía o empresa?
This Dot

## ¿Qué tipo de conector tiene tu notebook?

- [ ] HDMI
- [x] Mini DisplayPort
- [ ] VGA

## ¿Quieres agregar algo más?
La idea recién la comienzo a desarrollar. Prometo actualizar durante la semana y darles un título definitivo. Dependiendo del tiempo, podría enfocarme más en testing-library o en aspectos más generales del testing. Dejo fuera otros tests (servicios, pipes, etc). Gracias!

-----------
> Muchas Gracias! 
> El equipo de Angular Chile <3

**Comment by nicoavila** [comment]
Hola @flakolefluk 
Crees que sea posible agendar tu presentación para el 3º Meetup (fecha tentativa 29 de Agosto).
Muchas gracias!

**Comment by flakolefluk** [comment]
Seguro! 
;)

**Comment by nicoavila** [comment]
Genial! Muchas gracias!
